SECTION = "Network & Connectivity/Libraries"
SRPM_IS_LIB = "${PN}"
SRPM_IS_LIB = "libnl-cli"
SRPM_IS_LIB = "libnl-genl"
SRPM_IS_LIB = "libnl-idiag"
SRPM_IS_LIB = "libnl-nf"
SRPM_IS_LIB = "libnl-route"
